// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateThread(arg1: string): Promise<any>;
export function CheckBridge(): Promise<any>;
export function CreateTask(arg1: string,arg2: string): Promise<any>;
export function CreateThread(arg1: string): Promise<any>;
export function GetAppInfo(): Promise<string>;
export function GetRuntimeStatus(): Promise<any>;
