// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateThread(arg1) {
  return window["go"]["main"]["App"]["ActivateThread"](arg1);
}

export function AdvanceTask(arg1) {
  return window["go"]["main"]["App"]["AdvanceTask"](arg1);
}

export function CheckBridge() {
  return window["go"]["main"]["App"]["CheckBridge"]();
}

export function CreateTask(arg1, arg2) {
  return window["go"]["main"]["App"]["CreateTask"](arg1, arg2);
}

export function CreateThread(arg1) {
  return window["go"]["main"]["App"]["CreateThread"](arg1);
}

export function GetAppInfo() {
  return window["go"]["main"]["App"]["GetAppInfo"]();
}

export function GetRuntimeStatus() {
  return window["go"]["main"]["App"]["GetRuntimeStatus"]();
}
